### PR TITLE
moving a few response processing functions to utilities

### PR DESCRIPTION
**Pull request by yavorska-iryna**

### CODE REVIEW

**Review by dougollerenshaw — COMMENTED** [review]
@yavorska-iryna I'm trying to keep this repo organized as follows:
* top-level - general purpose functions that should be applicable to many projects (e.g., event_triggered_response, which will work for any timeseries)
* project-specific folders (e.g. `visual_behavior_ophys`) for utilities that operate on data structures that are specific to particular mindscope datasets. 

Of the functions in this PR, I think `index_of_nearest_value` probably belongs at the top level. I think the rest are pretty specific to the Visual Behavior dataset.

Would you mind rearranging a bit?

Also, if possible, can you add tests for these functions? 

I want to keep this repo as clean as possible so that we could conceivably merge some/all of this functionality into the AllenSDK at some point with confidence that everything is well tested and stable.

**Comment by dougollerenshaw** [comment]
Also, I've been trying to stick to the numpy style guide for docstrings. Mind editing to stick to these conventions?
https://numpydoc.readthedocs.io/en/latest/format.html

**Comment by yavorska-iryna** [comment]
@dougollerenshaw Just to confirm, top-level functions should go into general_utilities and the rest that are specific should go to "data_formating" unless they are not formatting (like plotting, etc, should have their own .py file)?

**Comment by dougollerenshaw** [comment]
@yavorska-iryna the way I've envisioned this is that general utilities go at the top level. I made a `general_utilities.py` and a `plotting_utilities.py` (currently empty) to organize those top level functions a bit, but both get brought to the top level in the `__init__.py` (see https://github.com/AllenInstitute/mindscope_utilities/blob/main/mindscope_utilities/__init__.py), so the user doesn't have to know which submodule these functions are saved in. I was following the example set by seaborn in structuring the top level this way (see https://github.com/mwaskom/seaborn/blob/master/seaborn/__init__.py).

For the project specific folders, I was envisioning much the same structure, but I've only made a `data_formatting.py` inside of `visual_behavior_ophys` so far. I think it'd also make sense to have a `general_utilities.py`, `plotting_utilities.py`, etc. Again, they are brought to the top level of the module in the `__init__.py`, which makes the import syntax simpler for the end user.

**Comment by dougollerenshaw** [comment]
Also, by way of example, setting up the `__init__.py` this way makes these two import statements interchangeable (both work). But the latter is simpler for the end user:

```python
from mindscope_utilities.general_utilities import event_triggered_response
from mindscope_utilities import event_triggered_response
```
And for project specific modules, both of these work but the latter is simpler:
```python
from mindscope_utilities.visual_behavior_ophys.data_formatting import build_tidy_cell_df
from mindscope_utilities.visual_behavior_ophys import build_tidy_cell_df
```

**Comment by yavorska-iryna** [comment]
Thank you for more details, this is very helpful for me to learn. I'll edit and try to organize analysis processing functions into correct modules + change docstring format.

**Comment by yavorska-iryna** [comment]
@DowntonCrabby @dougollerenshaw I moved three functions : index_of_nearest_value, slice_inds_and_offsets, get_eventlocked_traces to general utilities. 
* I renamed some ophys specific variables to more general. My reasoning that these functions can be used to slice any neural traces. These functions can also be used more generally to slice pupil or running traces around event (I would need to test that). 
* I propose using "timestamps" instead of "time". I think it's more common in the field and I believe timestamps is used in SDK too.
* Please review to make sure that variables and docstrings make sense. 
Thank you.

**Comment by dougollerenshaw** [comment]
@yavorska-iryna should we close this PR? It seems that most of this work has been included in other PRs.

**Pull request closed without merging**
